### ISSUE TITLE
Layer list display on iPhone

### ISSUE THREAD

**Issue by dpslwk** [emfcamp/map#41]
Layer names are getting odd stacking on my iPhone (14 Pro, Safari), in the browser and as installed home app

suspect this needs a CSS tweak

![IMG_1155](https://github.com/emfcamp/map/assets/234460/bdaeedc5-3f18-4394-8c75-88d38d73e82c)

**Comment by aliceisjustplaying** [comment]
yep same here on the 14PM

**Comment by dpslwk** [comment]
A css in in that repo,
just had a quick poke with iPad safari and remote web inspector 
its fine at 100% zoom but shows up at 115% zoom

seem to be this `font-size` change in the `@media` is cause some thing to overlap and push things around?
https://github.com/russss/maplibregl-layer-switcher/blob/c47df4934c2c9b2915d63cf81282028e48909dee/src/layerswitcher.css#L29


![IMG_1036](https://github.com/emfcamp/map/assets/234460/31fd0998-821d-4304-b2df-f2c50123df27)
same zoom just with that one css line disabled via inspector
![IMG_1037](https://github.com/emfcamp/map/assets/234460/f34b02b2-7080-4eb4-865c-81ac66d8570c)

**Comment by aliceisjustplaying** [comment]
oh my god that's amazing

**Comment by dpslwk** [comment]
can also reproduce on desktop safari with a responsive design view / narrower window and by increasing the font size

**Comment by russss** [comment]
Ahh, thanks! I can also reproduce it in Firefox desktop with the font size turned up so now I have a good chance of being able to fix it.

**Comment by russss** [comment]
Fixed in maplibregl-layer-switcher v1.2.4.
