### ISSUE TITLE
Use map with XYZ tile layer

### ISSUE THREAD

**Issue by harvy4002** [emfcamp/map#43]
I want to embed the EMF map into grafana, and it seems parts of it uses the XYZ map layer.

Is there a URL I can use to get all (or most) of the map in this kind of format. e.g. https://map.emfcamp.org/data/ortho/{z}/{x}/{y}

**Comment by russss** [comment]
Unfortunately not - the main layers use the Mapbox Vector Tiles standard which is not compatible with the older-style tiled map viewers.
